# -*- coding: utf-8 -*-
"""basis_expansion_evolution_SquareWell.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOMv_G4PMgj28JWA71VdXNokpGoPGFNM
"""

import numpy as np
import matplotlib.pyplot as plt

# Calcula la evolución usando la base del pozo cuadrado

hbar = 1e-34
L = 1e-5
m = 1.6e-27
Va = 3e-17
dt = 1e-6
v = 0.3
k = m * v / hbar

N = 30

# funciones de la base
dx = L / 1e4
x = np.arange(0, L + dx, dx)
sx = len(x)
f = np.zeros((N, sx))

for ja in range(N):
    # En Python el índice empieza en 0, pero la base (n) va de 1 a N
    n_base = ja + 1
    f[ja, :] = np.sqrt(2 / L) * np.sin(n_base * np.pi * x / L)

# Hamiltoniano diagonal
Hp = np.zeros((N, N))
for ja in range(N):
    n_base = ja + 1
    Hp[ja, ja] = n_base**2

Hp = Hp * (hbar**2) * (np.pi**2) / (2 * m * (L**2))

# Potencial
Vx = Va * ((x - (L / 2))**2)
V = np.zeros((N, N))
for ja in range(N):
    for jb in range(N):
        V[ja, jb] = dx * np.sum(f[ja, :] * Vx * f[jb, :])

H = Hp + V

# Diagonalizar
eval_vals, evec = np.linalg.eigh(H) # eigh es óptimo para matrices hermíticas/simétricas

# función inicial (1j es la unidad imaginaria en Python)
g = np.exp(-1j * k * x) * np.exp(-((x - L / 2)**2) / (2 * ((L / 10)**2)))
normg = dx * np.sum(g * np.conj(g))
g = g / np.sqrt(normg)

# expansión en eigenfunciones
cf0 = np.zeros(N, dtype=complex)
for ja in range(N):
    cf0[ja] = dx * np.sum(f[ja, :] * g)

cf = np.zeros(N, dtype=complex)
for ja in range(N):
    cf[ja] = np.dot(cf0, evec[:, ja])

# evolucion
plt.ion() # Activar modo interactivo para animación
fig, ax = plt.subplots()

for jb in range(30):
    t = jb * dt
    ft = np.zeros(N, dtype=complex)
    for ja in range(N):
        ft += cf[ja] * np.exp(-1j * eval_vals[ja] * t / hbar) * evec[:, ja]

    ftx = np.zeros_like(x, dtype=complex)
    for ja in range(N):
        ftx += ft[ja] * f[ja, :]

    ax.clear()
    # ftx * np.conj(ftx) da un número complejo con parte imaginaria 0. Se extrae la parte real.
    ax.plot(x, np.real(ftx * np.conj(ftx)))
    ax.set_xlim(0, L)
    ax.set_ylim(0, 6e6)
    ax.grid(True)

    plt.draw()
    plt.pause(0.1)

plt.ioff()
plt.show()