# -*- coding: utf-8 -*-
"""basis_expansion_evolution_HarmonicOscillator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOLcamLOyuY8ZmeME9p-9zFRXMMZrX5-
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.fft import fft, ifft

# Evolución en un potencial armónico. Solución con el método de operadores partidos
# (split operator). Evolucion del operador de momento en el espacio de momento, y
# para el operador de posición en el espacio de posición.
# Mostrar: potencial usado, variación en el ancho de la función de onda y el hecho
# de que la función regrese a la condición inicial a diferencia del paquete libre,
# bosquejar la evolución en el espacio de momentos y en el espacio fase, estresar
# sobre como se incorporó el potencial y que puede ser para un potencial arbitrario
# inclusive uno dependiente del tiempo. Dejar de tarea el caso de la reflexión
# cuántica utilizando éste método y algún otro que seleccionen y un potencial
# cuártico por el método de la solución matricial y otro método que seleccionen.

hbar = 1e-34       # constante de Planck/2pi
m = 1.6e-27        # masa de la partícula (átomo)
L = 3e-6           # tamaño del pozo
Nx = 2**10         # número de puntos en el eje x
x = np.arange(0, L, L/Nx)

######## Función inicial
wf = L / 10        # ancho gaussiana
v = 10             # velocidad del paquete
kv = m * v / hbar
f = np.exp(-(((x - (L / 2)) / wf)**2) + 1j * kv * x)    # función de onda inicial
normf = (L / Nx) * np.vdot(f, f)      # factor de normalización de f
f = f / np.sqrt(normf)                # f normalizada
fp = fft(f)                           # función en el espacio de momentos

kp = np.arange(0, Nx) * 2 * np.pi / L
# Vector de onda ordenado (traducción exacta de la lógica de índices de MATLAB)
kp[Nx//2 + 1 : Nx] = -kp[Nx//2 - 1 : 0 : -1]

####### Potencial
Vc = L / 2
wpot = 1e7
V = (m * (wpot**2) / 2) * ((x - Vc)**2)

plt.ion()
fig, ax = plt.subplots()
ax.plot(x, V)
plt.draw()
plt.pause(1)

####### Evolución del paquete
tstep = 90         # número de pasos temporales
dt = 1e-8          # tamaño de paso temporal
wn = hbar * (kp**2) / (2 * m)
wnx = V / hbar
ftp = fp

for jb in range(tstep + 1):
    ftp = ftp * np.exp(-1j * wn * dt)
    ft = ifft(ftp)
    ft = ft * np.exp(-1j * wnx * dt)
    ftp = fft(ft)

    ax.clear()
    ax.plot(x, np.real(ft * np.conj(ft)))
    ax.set_xlim(0, L)
    ax.set_ylim(0, 2e7)
    plt.draw()
    plt.pause(0.1)

plt.ioff()
plt.show()